### ISSUE TITLE
Doesn't work on ProcessWire 3

### ISSUE THREAD

**Issue by Jugibur** [justonestep/processwire-imageextra#12]
I have installed a fresh PW 3.0.8 with ImageExtra.

But the uploading process of an image doesn't get finished.
It shows a loading value of 100%, but the activity indicator still rotating.
Also saving the page doesn't show the image after that.

**Comment by justonestep** [comment]
Hi,
ImageExtra is not yet ready for PW 3.X, I had no time to test it so far. Thanks for the report, I'll test it soon.

**Comment by justonestep** [comment]
Fixed in develop branch.
