### ISSUE TITLE
Write to custom fields using API does not work

### ISSUE THREAD

**Issue by mn-martin** [justonestep/processwire-imageextra#15]
```
$page->image->customfield = 'foo';
$page->save();
```

deose not work.

**Comment by mn-martin** [comment]
Found a solution:

```
$page->setOutputFormatting(false);
$page->image->trackChange('customfield');
$page->image->first()->set('customfield', "Works");
$page->save();
$page->setOutputFormatting(true);
```

**Comment by mn-martin** [comment]
In following context it does not seem to be possible to manipulate contents of custom fields:

```
$this->pages->addHookBefore( 'save', $this, 'manipulateContentsOfCustomFields' );
```

Manipulating the description has always worked perfectly in this case for me thought...

**Comment by mn-martin** [comment]
If anyone else runs into this: 

As a workaround I'm now adding an after hook. In this case I can't save the page but single fields to prevent infinite loops. Using my above posted snippet and $page->save('fieldname') will work but that's really ugly thought :-/

**Comment by justonestep** [comment]
Hi,

I tested both scenarios and found a solution for each of them.

**Writing custom fields (as you described above):**
```php
foreach ($page->images as $img) {
  $page->setOutputFormatting(false);
  $page->images->trackChange('caption');
  $img->caption = 'Test';
  $page->save();
  $page->setOutputFormatting(true);
}
```

**Use a hook onBeforePageSave:**
```php
$this->addHookBefore('Pages::save', $this, 'manipulateContentsOfCustomFields');

public function manipulateContentsOfCustomFields(HookEvent $event) {
  $page = $event->arguments(0);

  foreach ($page->images as $img) {
    $page->images->trackChange('caption');
    $img->caption = 'Test2';
  }
}
```

Tested with PW3.0.18 and ImageExtra1.0.0 (branch develop atm).

**Comment by mn-martin** [comment]
> Tested with PW3.0.18 and ImageExtra1.0.0 (branch develop atm).

2.7.2 - 0.0.3 here and the issues are ongoing ofc. 

Today I was trying to write to one of my custom fields from FormBuilderProcessor::savePageDone Hook. It was impossible no matter what. I fixed it using following code:

```
/** @var \WireDatabasePDO $database */
$database = wire('database');

$query = $database->prepare('UPDATE field_images SET custom = :custom WHERE pages_id = :pageId');
$query->execute([':custom' => "[\"{$custom}\"]", ':pageId' => (string) $page->id]);
```

Would you suggest upgrading to 1.0.0 even thought I'll stay at ProcessWire 2.x (2.8 will be 3.x without namespaces)

**Comment by justonestep** [comment]
Hi,
unfortunately I can't give a suggestion because I never used FormBuilder or PW 2.8. You could give it a try and install version 1.0.0 (before backup everything ;) ).
Sorry.
