### ISSUE TITLE
Call to a member function save() on a non-object (line 671 of ImageExtra.module)

### ISSUE THREAD

**Issue by jlahijani** [justonestep/processwire-imageextra#18]
When using the "develop" brand on PW 3.0.22 and adding an image, it causes the error as described in the title.

When I disable the line:

```
$p->save($name);
```

...which is inside the fileAddedExtra function, it saves fine.

**Comment by justonestep** [comment]
You're not using the version with PW 3.0.x compatibility as you said. Having a look into `fileAddedExtra` function in [branch develop](https://github.com/justonestep/processwire-imageextra/blob/develop/ImageExtra.module#L695), there is no `$p->save($name);` entry anymore. 

Please make sure you're using branch develop. Then everything should work as expected.

I've the module working in a lot of 3.0.x instances without any problem. I just installed the latest PW 3.0.24 version and tested again, everything works as expected. I'm able to upload an image, no error message occurs. The image gets saved as well as the extra data.
