### ISSUE TITLE
Caption fields don't allow $

### ISSUE THREAD

**Issue by mackski** [justonestep/processwire-imageextra#2]
Traced this problem down to:
// insert additional output
$out = preg_replace('/(<input\sclass=\'InputfieldFileSort\')/', $outAdditional . '$1', $out);

Adding this function mentioned here resolves the issue:
http://us1.php.net/manual/en/function.preg-replace.php#103985

SO:

// fix any back references, ie: $100 - $n has special meaning in preg_replace
$outAdditional = preg_replace('/\$(\d)/', '\\\$$1', $outAdditional);

// insert additional output
$out = preg_replace('/(<input\sclass=\'InputfieldFileSort\')/', $outAdditional . '$1', $out);

**Comment by justonestep** [comment]
wow, I can reproduce this :) I didn't though about having "$" in the input field. The fix is now in the master branch as well. Thanks.
