### ISSUE TITLE
Choose page link not working

### ISSUE THREAD

**Issue by adrianbj** [justonestep/processwire-imageextra#6]
https://processwire.com/talk/topic/9056-module-image-extra/?p=106684

You just need to load "InputfieldPageListSelect.min.js" in the module, then it works as expected.

**Comment by adrianbj** [comment]
Actually, it looks like this might only be an issue when the imagextra field is inside a PageTable and/or only when the user is not a superuser.

**Comment by justonestep** [comment]
Fixed in develop branch.
