### ISSUE TITLE
Removing extra fields from the config results in fatal error.

### ISSUE THREAD

**Issue by adrianbj** [justonestep/processwire-imageextra#9]
If you remove one of the "Add other text input fields" the field/column is not removed from the DB. This results in a fatal error and the images uploaded to the field are lost. You have to manually edit the DB table to remove the fields to get things working again.

I know you are having trouble reproducing this - I am seeing it on multiple PW installs, but I will try to test on a clean install at some point to see if there is some other interaction causing the problem at my end.

https://processwire.com/talk/topic/9056-module-image-extra/?p=106868

**Comment by justonestep** [comment]
Tried to reproduce this using it inside a page table. But everything works. Could you please explain where you use such an image field? Or could you test setting up a fresh installation, installing ImageExtra and adding some fields to the predefined `images` field? Does the error occur there as well?

**Comment by mn-martin** [comment]
You're making the fields be NOT NULL in the DB. This is causing issues when you remove the fields or uninstall this module. (Just remove the NOT NULL and everythings fine)

**Comment by lanceosborne** [comment]
I can confirm that an extra **caption** field after uninstalling the ImageExtra 0.0.2 module caused the following error when attempting to upload an image: **SQLSTATE[HY000]: General error: 1364 Field 'caption' doesn't have a default value**

https://processwire.com/talk/topic/13078-error-when-uploading-image-field-caption-doesnt-have-a-default-value/

**Comment by justonestep** [comment]
Thanks for the feedback, now I've got an idea what could cause this behaviour. I guess, this is related to `sql_mode` defined in a `my.cnf` file. I removed `STRICT_TRANS_TABLES`, maybe this is why I didn't get an error. I'll test this!

**Comment by justonestep** [comment]
```
SQLSTATE[HY000]: General error: 1364 Field 'bla' doesn't have a default value
```
Now I'm able to reproduce (and fix) this error 👍

**Comment by justonestep** [comment]
Fixed in develop and master. Unfortunately it works only for newly created fields.
